// Generated by https://quicktype.io

export interface Assignment {
  name:          string;
  description:   string;
  beingDoneById: number;
  projectId:     number;
  priority:      number;
  stage:         number;
  id:            number;
  createdDate:   string;
  descriptionURL: string;
  designURL:     string;
  createdBy:     string;
  updatedBy:     string;
  updatedAt:     string;
}
