// Generated by https://quicktype.io

export interface Project {
  name:        string;
  description: string;
  id:          number;
  createdDate: string;
  createdBy:   string;
  updatedBy:   string;
  updatedAt:   string;
}
