// Generated by https://quicktype.io

export interface User {
  name:        string;
  lastName:    string;
  email:       string;
  password:    string;
  status:      string;
  linkedIn:    string;
  gitHub:      string;
  avatar:      string;
  userType:    string;
  id:          number;
  createdDate: string;
  createdBy:   number;
  updatedBy:   number;
  updatedAt:   string;
}
